language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

env:
  global:
  - NEXUS_USERNAME=travis
  - secure: V5EK5xgOI/NzfyefqZtR5SUWZYi627fmuF9Qar32IiiX+jNa4xkp30J2ZXqIhV4ff9/KlDu1IdovuXCDGwf46fEKQwWJHajDqbztqdKObcKcKecqlO01DYyAey+l+yy2eOB0bbS1spK82LczpJDPBgXYx6AJDkPrtJmnwLU00PY=

script:
  - mvn -DfailOnServiceError=false clean deploy jacoco:report coveralls:report --settings travis-maven-settings.xml
